module.exports = {
    AccountRoleType: require('./account-role-type'),
    CreatureAttributeId: require('./creature-attribute-id'),
    CreatureAttributeTypeId: require('./creature-attribute-type-id'),
    CreatureCalculation: require('./creature-calculations'),
    CreatureCosts: require('./creature-costs'),
    CreaturePoints: require('./creature-points'),
    CreatureSkillId: require('./creature-skill-id'),
    CreatureTypeId: require('./creature-type-id'),
    CreatureWeaponTypeId: require('./creature-weapon-type-id'),
    FieldTitle: require('./database-field-titles'),
    Plural: require('./database-table-plural'),
    DateFormat: require('./date-format'),
    Dice: require('./dice'),
    Expiry: require('./expiry'),
    HeaderKey: require('./header-key'),
    OTPAuth: require('./otp-auth'),
    TokenKey: require('./token-key'),
};
